kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  namespace: <replace with namespace>
spec:
  storageClassName: <replace with your block storage class>
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi