kind: Secret
apiVersion: v1
metadata:
  name: mssql
  namespace: sql-server
  uid: 4ae3f450-a1ab-48ee-9b0c-da12f999b774
  resourceVersion: '1441025'
  creationTimestamp: '2026-04-02T13:26:26Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2026-04-02T13:28:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:MSSQL_SA_PASSWORD': {}
        'f:type': {}
data:
  MSSQL_SA_PASSWORD: QDEyMzQ1Njc4YkE=
type: Opaque
